### ISSUE TITLE
Cannot install latest version 

### ISSUE THREAD

**Issue by DavidAuditore99** [PooyaHekmati/music_embedding#2] opened 2024-01-16 19:07 UTC
Collecting music_embedding
  Downloading music_embedding-1.0.1.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3q/rvstvxyd7_ngxqtl0037hbvc0000gn/T/pip-install-mh00qcme/music-embedding_480e28160b8f4213843d04eafd182cf2/setup.py", line 27, in <module>
          long_description=_get_long_description(),
                           ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3q/rvstvxyd7_ngxqtl0037hbvc0000gn/T/pip-install-mh00qcme/music-embedding_480e28160b8f4213843d04eafd182cf2/setup.py", line 5, in _get_long_description
          with open(str(Path(__file__).parent / "doc" / "source" / "index.rst"), "r") as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/3q/rvstvxyd7_ngxqtl0037hbvc0000gn/T/pip-install-mh00qcme/music-embedding_480e28160b8f4213843d04eafd182cf2/doc/source/index.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by PooyaHekmati** [comment] 2024-01-26 23:59
Thanks @DavidAuditore99 , the issue is now fixed in the latest version.

**Closed by PooyaHekmati** 2024-01-26 23:59 UTC
